package main

import (
	"context"
	"flag"
	"fmt"

	"cloud.google.com/go/bigquery"
	"cloud.google.com/go/bigtable"
	"github.com/m-lab/go/rtx"
	"github.com/m-lab/signal-searcher/analyzer"
	"github.com/m-lab/signal-searcher/sequencer"
	"google.golang.org/api/iterator"
)

var (
	project = flag.String("project", "measurement-lab", "The name of the cloud project the bigtables are in")

	mainCtx, mainCancel = context.WithCancel(context.Background())

	// A variable to allow injection of a fake bigtable client for testing.
	bigtableNewClient = bigtable.NewClient
)

// This takes monthly download data and discovers instances of year-long
// sustained drops in Internet performance. It is currently hardcoded to only
// work with monthly data. It likely has lots of other issues too. Nevertheless,
// it finds 17,000 results, which is a good start.
func main() {
	defer mainCancel()
	flag.Parse()

	client, err := bigquery.NewClient(mainCtx, *project)
	rtx.Must(err, "Could not connect to bigquery")

	query := `
	with web100_performance_multiples AS (
		SELECT test_id,
		  'web100' AS type,
		  connection_spec.client.network.asn as asn,
		  connection_spec.client_geolocation.country_name as country,
		  partition_date AS date,
		  web100_log_entry.connection_spec.remote_ip AS client,
		  8 * (web100_log_entry.snap.HCThruOctetsAcked
			  / (web100_log_entry.snap.SndLimTimeRwin +
				  web100_log_entry.snap.SndLimTimeCwnd +
				  web100_log_entry.snap.SndLimTimeSnd))
			AS bandwidth,
		  (web100_log_entry.snap.SndLimTimeRwin +
			  web100_log_entry.snap.SndLimTimeCwnd +
			  web100_log_entry.snap.SndLimTimeSnd) / 1000000.0
			AS duration
		FROM ` + "`measurement-lab.ndt.web100`" + `
		WHERE web100_log_entry.connection_spec.local_ip IS NOT NULL
		AND web100_log_entry.connection_spec.remote_ip IS NOT NULL
		-- Download direction
		AND connection_spec.data_direction IS NOT NULL
		AND connection_spec.data_direction = 1
		AND web100_log_entry.snap.HCThruOctetsAcked IS NOT NULL
		AND web100_log_entry.snap.HCThruOctetsAcked > 0
		-- Sum of SndLimTime* have real values.
		AND web100_log_entry.snap.SndLimTimeRwin IS NOT NULL
		AND web100_log_entry.snap.SndLimTimeCwnd IS NOT NULL
		AND web100_log_entry.snap.SndLimTimeSnd IS NOT NULL
	  ),
	  -- Next the data from the new platform, making sure to use socket-level
	  -- statistics instead of NDT's application-level statistics.
	  -- (This is to work around a bug in ndt-server -
	  --    https://github.com/m-lab/ndt-server/issues/207 )
	  tcpinfo_performance_multiples AS (
		SELECT test_id,
		  'tcpinfo' AS type,
		  CAST(Client.Network.Systems[ORDINAL(1)].ASNs[ORDINAL(1)] AS STRING) as asn,
		  Client.Geo.country_name as country,
		  ndt5.partition_date AS date,
		  result.ClientIP AS client,
		  (FinalSnapshot.TCPInfo.BytesAcked*8/1000000)
			  /(TIMESTAMP_DIFF(result.S2C.EndTime,
							   result.S2C.StartTime,
							   MILLISECOND)/1000)
			AS bandwidth,
		  TIMESTAMP_DIFF(result.S2C.EndTime,
						 result.S2C.StartTime,
						 MILLISECOND)/1000
			AS duration
		FROM ` + "`measurement-lab.ndt.ndt5`" + ` AS ndt5
		  INNER JOIN ` + "`measurement-lab.ndt.tcpinfo`" + `
		  ON (result.S2C.UUID = UUID)
		WHERE result.S2C IS NOT NULL
		AND result.S2C.ClientIP IS NOT NULL
		AND result.S2C.MeanThroughputMbps > 0
	  ),
	  performance_multiples_unfiltered AS (
		SELECT * FROM web100_performance_multiples
		UNION ALL
		SELECT * FROM tcpinfo_performance_multiples
	  ),
	  -- Now that the data has a unified schema, filter it:
	  --  1) A 10 second transfer should take between 9 and 20 seconds, even
	  --     accounting for client/server clock skew
	  --  2) Only those streams that averaged greater than 10Kbps, as below
	  --     that is poorly measured by many popular clients
	  --  3) Eliminate the results generated by M-Lab's OA&M infrastructure
	  --  4) No mlab1 machines, because their client pool is known to be
	  --     different
	  --  5) No yul02 machines, because mlab3.yul02 was in maintenance mode
	  --     for the month of September.
	  performance_multiples AS (
		SELECT asn, country, date, bandwidth
		FROM performance_multiples_unfiltered
		WHERE
		   -- A 10 second download should take between 9 and 20 seconds
		  duration BETWEEN 9 AND 20
		   -- Over 10kbps
		  AND bandwidth > .01
		  -- These IPs are used by M-Lab's OA&M infrastructure
		  AND client NOT IN ("45.56.98.222", "35.192.37.249", "35.225.75.192",
			  "2600:3c03::f03c:91ff:fe33:819", "23.228.128.99",
			  "2605:a601:f1ff:fffe::99")
	  ),
	  country_as_summary_by_month as (
		SELECT asn, country, EXTRACT(YEAR FROM date) as year, EXTRACT(MONTH FROM date) as month,
			APPROX_QUANTILES(bandwidth,100)[ORDINAL(50)] as median_bandwidth, COUNT(*) as count
		FROM performance_multiples
		WHERE asn IS NOT NULL
			AND country IS NOT NULL
			AND date IS NOT NULL
			AND bandwidth IS NOT NULL
		GROUP BY country, asn, year, month
		ORDER BY country, asn, year, month
	  )
	  SELECT *
	  FROM country_as_summary_by_month
	  WHERE median_bandwidth IS NOT NULL
	    AND count > 100
`

	q := client.Query(query)
	j, err := q.Run(mainCtx)
	rtx.Must(err, "Could not execute query")

	s, c := sequencer.New()

	go func() {
		ri, err := j.Read(mainCtx)
		rtx.Must(err, "Could not make iterator")
		var row map[string]bigquery.Value
		for err = ri.Next(&row); err != iterator.Done; err = ri.Next(&row) {
			s.ProcessBQMap(row)
		}
		s.Done()
	}()

	fmt.Println("TestsAffected, AS, LocationCode, Start, End, URL")
	for seq := range c {
		if len(seq.Seq) <= 24 {
			continue
		}

		for _, incident := range analyzer.FindPerformanceDrops(seq) {
			fmt.Printf(
				"%d, %s, %s, %s, %s, %s\n",
				incident.AffectedCount, seq.Key.ASN, seq.Key.Loc, incident.Start.Format("2006-01-02"), incident.End.Format("2006-01-02"), incident.URL(seq.Key))
		}
	}
}
